version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/rlcraft:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
      MEMORY: 2g
      OPS: itzg
    ports:
      - 25565:25565
