version: "3.7"

services:
  mc:
    image: mc
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/rad:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      DEBUG: "true"
      CF_SERVER_MOD: /modpacks/RAD-Serverpack-1.45.zip
      OVERRIDE_SERVER_PROPERTIES: "true"
      MOTD: "New Beginnings V1.45"
      MAX_PLAYERS: "4"
      MEMORY: 2g
    ports:
      - 25565:25565
