version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/skyopolis-4:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/skyopolis-4-server.zip
      DEBUG: "true"
      MEMORY: 2g
      OPS: itzg
    ports:
      - 25565:25565
