version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/valhelsia3:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Valhelsia+3-3.2.4-SERVER.zip
      MEMORY: 2g
      OPS: itzg
    ports:
      - 25565:25565
