version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/eternal:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Eternal+(ServerPack+1.3.7.1).zip
      MEMORY: 2g
      DEBUG: "true"
      OPS: itzg
      USE_MODPACK_START_SCRIPT: "false"
    ports:
      - 25565:25565
