version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/better-minecraft:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: "/modpacks/Better+Minecraft+Server+Pack+[OTV+Edition]+v2.zip"
      MEMORY: 2g
      OPS: itzg
    ports:
      - 25565:25565
