version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/enigmatica6:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.4.10.zip
      MEMORY: 2g
      OPS: itzg
    ports:
      - 25565:25565
