version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - ../modpacks:/modpacks:ro
      - ../data/skyfactory4:/data
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/SkyFactory-4_Server_4.2.2.zip
      MEMORY: 2g
    ports:
      - 25565:25565
